# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_material', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'FoodMaterial',
            },
        ),
        migrations.CreateModel(
            name='FoodMaterialLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'FoodMaterialLevel',
            },
        ),
        migrations.AddField(
            model_name='foodmaterial',
            name='food_material_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delicious_hometown.FoodMaterialLevel'),
        ),
    ]
