# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-06 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_hometown', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmaterial',
            name='food_material_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delicious_hometown.FoodMaterialLevel'),
        ),
    ]
