# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-07 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_hometown', '0002_auto_20181007_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, verbose_name='账户')),
                ('password', models.CharField(max_length=12, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='用户名')),
                ('energy', models.IntegerField(verbose_name='体力')),
                ('level', models.IntegerField(verbose_name='等级')),
                ('coin', models.IntegerField(verbose_name='金币')),
                ('wing', models.IntegerField(default=0, verbose_name='元宝')),
                ('street', models.IntegerField(choices=[(1, '湖南街'), (2, '广东街'), (3, '四川街'), (4, '福建街'), (5, '山东街'), (6, '浙江街'), (7, '江苏街'), (8, '综合一街'), (9, '综合二街')], null=True, verbose_name='街道')),
            ],
        ),
        migrations.AlterField(
            model_name='foodmateriallevel',
            name='name',
            field=models.CharField(max_length=12, verbose_name='食材等级'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delicious_hometown.User'),
        ),
    ]
