# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-07 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_hometown', '0004_auto_20181007_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='account_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delicious_hometown.Account'),
            preserve_default=False,
        ),
    ]
