# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-07 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_hometown', '0006_auto_20181007_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delicious_hometown.FoodMaterial')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delicious_hometown.User')),
            ],
        ),
    ]
