# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-07 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_hometown', '0007_ambry'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ambry',
            table='Ambry',
        ),
    ]
