# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-07 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_hometown', '0009_auto_20181007_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_id',
            new_name='account',
        ),
    ]
