# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-08 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_hometown', '0010_auto_20181008_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='道具名称')),
                ('introdutions', models.CharField(max_length=128, verbose_name='道具介绍')),
            ],
            options={
                'db_table': 'Prop',
            },
        ),
        migrations.CreateModel(
            name='PropLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='道具类别')),
            ],
            options={
                'db_table': 'PropLevel',
            },
        ),
        migrations.AddField(
            model_name='prop',
            name='prop_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delicious_hometown.PropLevel'),
        ),
    ]
