# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-08 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_hometown', '0011_auto_20181008_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='price',
            field=models.IntegerField(default=2, verbose_name='价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prop',
            name='price_class',
            field=models.IntegerField(choices=[(1, '金币'), (2, '元宝')], default=2, verbose_name='需要的货币'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='coin',
            field=models.IntegerField(default=0, verbose_name='金币'),
        ),
    ]
