# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-08 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_hometown', '0012_auto_20181008_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backpack_prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delicious_hometown.Prop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delicious_hometown.User')),
            ],
        ),
    ]
