# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-08 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_hometown', '0013_backpack'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='backpack',
            table='Backpack',
        ),
    ]
