# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-10 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_hometown', '0014_auto_20181008_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'RecipeClass',
            },
        ),
        migrations.CreateModel(
            name='RecipeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '普通'), (2, '上品'), (3, '极品'), (4, '银牌'), (5, '金牌')], verbose_name='菜谱等级')),
                ('price', models.IntegerField(verbose_name='售价')),
                ('oil_used', models.IntegerField(verbose_name='耗油量')),
                ('experience', models.IntegerField(verbose_name='获得经验')),
                ('recipe_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delicious_hometown.RecipeClass', verbose_name='菜系')),
            ],
            options={
                'db_table': 'RecipeLevel',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='菜谱名称')),
                ('introduce', models.CharField(max_length=1024, verbose_name='详细做法')),
            ],
            options={
                'db_table': 'Reataurant',
            },
        ),
        migrations.CreateModel(
            name='RestaurantRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delicious_hometown.RecipeLevel')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delicious_hometown.Restaurant')),
            ],
        ),
    ]
