# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-10 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_hometown', '0015_recipeclass_recipelevel_restaurant_restaurantrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='introduce',
            field=models.CharField(max_length=1024, null=True, verbose_name='详细做法'),
        ),
    ]
