# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-12 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_hometown', '0022_auto_20181012_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='choice_market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delicious_hometown.FoodMaterial')),
            ],
        ),
    ]
