# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-12 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_hometown', '0023_choice_market'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='choice_market',
            new_name='ChoiceMarket',
        ),
        migrations.AlterModelTable(
            name='choicemarket',
            table='ChoiceMarket',
        ),
    ]
