# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-12 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious_hometown', '0024_auto_20181012_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicemarket',
            name='test',
            field=models.IntegerField(default=1),
        ),
    ]
